### ISSUE TITLE
Support for retail executables?

### ISSUE THREAD

**Issue by RecklessGlue540** [Fire-Head/MHNoDRM#1]
Could support for retail executables without having to rely on NoCD cracks be added?

**Comment by Fire-Head** [comment]
No, the game is not an abandonware yet and still can be purchased digitally which may cause possible legal consequences.
The only goal the project can afford is to fix already broken Steam release, and that’s done.

**Comment by RecklessGlue540** [comment]
Riight... I understand. Closing this.
